# Generated by Django 5.1.4 on 2024-12-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit'), ('money transfer', 'Money Transfer'), ('card payment', 'Card Payment')], max_length=20),
        ),
    ]
