# Generated by Django 5.1.4 on 2024-12-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_user',
            new_name='reciever_user',
        ),
    ]
