# Generated by Django 5.1.4 on 2024-12-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_receiver_user_transaction_reciever_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_password',
            field=models.CharField(max_length=255),
        ),
    ]
