# Generated by Django 5.1.4 on 2024-12-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transaction_sender_card_transaction_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciever_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
