# Generated by Django 5.1.4 on 2024-12-15 20:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(9, 'Email length must be greater than 9'), django.core.validators.EmailValidator('Please enter a valid email')])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, 'Email length must be greater than 8')])),
                ('number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(9, 'Number can not be smaller than 9')])),
                ('birthday_date', models.DateField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
