# Generated by Django 5.1.4 on 2024-12-15 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(9, 'Number can not be smaller than 9')]),
        ),
    ]
